### ISSUE TITLE
gips_project missing lines at bottom of image

### ISSUE THREAD

**Issue by dchowdhury** [Applied-GeoSolutions/gippy#11]
gips_project using shapefile is creating results with lines of nodata at the bottom. Further, there is a ramp in the number of missing lines from edge to center of image.

dchowdhury@rio:/scratch/dchowdhury/RICE_DSS/Asia/MYANMAR$ gips_project landsat -s Shapefiles/Myanmar_chunkA.shp -d 2014,2015 -p ndvi satvi lswi bqashadow --numprocs 4 --res 0.00016666 0.00016666

Pink is shapefile layer in attachment.

![bug2](https://cloud.githubusercontent.com/assets/8417829/16926308/1b0d8266-4cf6-11e6-89d9-cd75b8c97e45.png)

![bug1](https://cloud.githubusercontent.com/assets/8417829/16926251/e66d9366-4cf5-11e6-90cc-2437ef8884b4.png)

**Comment by ircwaves** [comment]
fixed via https://github.com/gipit/gippy/pull/168
