### ISSUE TITLE
ACCA shadow smear misaligned

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gippy#8]
The shadow-smear and original ACCA cloud mask are not aligned:
![pre-smear-fix](https://cloud.githubusercontent.com/assets/9936909/13060165/8b24795a-d3fd-11e5-9847-75780dacf8fe.png)

**Comment by ircwaves** [comment]
2723f3a fixes it.
![post-smear-fix](https://cloud.githubusercontent.com/assets/9936909/13060235/01ec1642-d3fe-11e5-9dcf-16495451fa71.png)

**Comment by mcorbiere** [comment]
In relation to this issue, when masks are applied to an image through gips, the masks are added to the metadata like this:
....
Metadata:
  AREA_OR_POINT=Area
  MASKS=2007242_LE7_acca 2007242_LE7_fmask
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
....

Maybe we should add the versioning of the acca mask to the metadata as we process new ones.

**Comment by ircwaves** [comment]
is this mask applied via `gips_mask`?

**Comment by mcorbiere** [comment]
yeah this one was gips_mask on ref image using acca and fmask

**Comment by ircwaves** [comment]
OK.

**Comment by ircwaves** [comment]
The original issue is resolved.  @mcorbiere's comment is a good enhancement request that should be made an issue on its own...and in gips ;)
